export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './chemicalTestController.service';
import { ChemicalTestControllerService } from './chemicalTestController.service';
export * from './complainController.service';
import { ComplainControllerService } from './complainController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './customerPaymentController.service';
import { CustomerPaymentControllerService } from './customerPaymentController.service';
export * from './deliveryController.service';
import { DeliveryControllerService } from './deliveryController.service';
export * from './discountController.service';
import { DiscountControllerService } from './discountController.service';
export * from './disposalController.service';
import { DisposalControllerService } from './disposalController.service';
export * from './employeeController.service';
import { EmployeeControllerService } from './employeeController.service';
export * from './imageUploadController.service';
import { ImageUploadControllerService } from './imageUploadController.service';
export * from './inventoryController.service';
import { InventoryControllerService } from './inventoryController.service';
export * from './itemController.service';
import { ItemControllerService } from './itemController.service';
export * from './notificationController.service';
import { NotificationControllerService } from './notificationController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './productInboundController.service';
import { ProductInboundControllerService } from './productInboundController.service';
export * from './productOutboundController.service';
import { ProductOutboundControllerService } from './productOutboundController.service';
export * from './purchaseController.service';
import { PurchaseControllerService } from './purchaseController.service';
export * from './purchaseOrderController.service';
import { PurchaseOrderControllerService } from './purchaseOrderController.service';
export * from './roleController.service';
import { RoleControllerService } from './roleController.service';
export * from './saleController.service';
import { SaleControllerService } from './saleController.service';
export * from './supplierController.service';
import { SupplierControllerService } from './supplierController.service';
export * from './supplierPaymentController.service';
import { SupplierPaymentControllerService } from './supplierPaymentController.service';
export * from './supplierRefundController.service';
import { SupplierRefundControllerService } from './supplierRefundController.service';
export * from './supplierReturnController.service';
import { SupplierReturnControllerService } from './supplierReturnController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './vehicleController.service';
import { VehicleControllerService } from './vehicleController.service';
export const APIS = [AuthenticationControllerService, ChemicalTestControllerService, ComplainControllerService, CustomerControllerService, CustomerPaymentControllerService, DeliveryControllerService, DiscountControllerService, DisposalControllerService, EmployeeControllerService, ImageUploadControllerService, InventoryControllerService, ItemControllerService, NotificationControllerService, OrderControllerService, ProductInboundControllerService, ProductOutboundControllerService, PurchaseControllerService, PurchaseOrderControllerService, RoleControllerService, SaleControllerService, SupplierControllerService, SupplierPaymentControllerService, SupplierRefundControllerService, SupplierReturnControllerService, UserControllerService, VehicleControllerService];
