export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './itemController.service';
import { ItemControllerService } from './itemController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './roleController.service';
import { RoleControllerService } from './roleController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthenticationControllerService, CustomerControllerService, ItemControllerService, OrderControllerService, RoleControllerService, UserControllerService];
