/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Delivery } from '../model/delivery';
import { DeliveryList } from '../model/deliveryList';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DeliveryControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * View a list of deliveries
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllDeliveriesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<DeliveryList>;
    public getAllDeliveriesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DeliveryList>>;
    public getAllDeliveriesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DeliveryList>>;
    public getAllDeliveriesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DeliveryList>(`${this.basePath}/delivery`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get delivery by id
     * 
     * @param deliveryId deliveryId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDeliveryByIdUsingGET(deliveryId: string, observe?: 'body', reportProgress?: boolean): Observable<Delivery>;
    public getDeliveryByIdUsingGET(deliveryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Delivery>>;
    public getDeliveryByIdUsingGET(deliveryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Delivery>>;
    public getDeliveryByIdUsingGET(deliveryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (deliveryId === null || deliveryId === undefined) {
            throw new Error('Required parameter deliveryId was null or undefined when calling getDeliveryByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Delivery>(`${this.basePath}/delivery/${encodeURIComponent(String(deliveryId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update delivery details
     * 
     * @param delivery delivery
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateDeliveryUsingPUT(delivery: Delivery, observe?: 'body', reportProgress?: boolean): Observable<Delivery>;
    public updateDeliveryUsingPUT(delivery: Delivery, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Delivery>>;
    public updateDeliveryUsingPUT(delivery: Delivery, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Delivery>>;
    public updateDeliveryUsingPUT(delivery: Delivery, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (delivery === null || delivery === undefined) {
            throw new Error('Required parameter delivery was null or undefined when calling updateDeliveryUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Delivery>(`${this.basePath}/delivery`,
            delivery,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
