/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Discount } from '../model/discount';
import { TransactionDetails } from '../model/transactionDetails';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DiscountControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get discount by category and type
     * 
     * @param category category
     * @param type type
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDiscountUsingGET(category: string, type: string, observe?: 'body', reportProgress?: boolean): Observable<Discount>;
    public getDiscountUsingGET(category: string, type: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Discount>>;
    public getDiscountUsingGET(category: string, type: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Discount>>;
    public getDiscountUsingGET(category: string, type: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling getDiscountUsingGET.');
        }

        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling getDiscountUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Discount>(`${this.basePath}/discount/${encodeURIComponent(String(category))}/${encodeURIComponent(String(type))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get calculated transaction details
     * 
     * @param transactionDetails transactionDetails
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTransactionDetailsUsingPOST(transactionDetails: TransactionDetails, observe?: 'body', reportProgress?: boolean): Observable<TransactionDetails>;
    public getTransactionDetailsUsingPOST(transactionDetails: TransactionDetails, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TransactionDetails>>;
    public getTransactionDetailsUsingPOST(transactionDetails: TransactionDetails, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TransactionDetails>>;
    public getTransactionDetailsUsingPOST(transactionDetails: TransactionDetails, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (transactionDetails === null || transactionDetails === undefined) {
            throw new Error('Required parameter transactionDetails was null or undefined when calling getTransactionDetailsUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<TransactionDetails>(`${this.basePath}/discount`,
            transactionDetails,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
