/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Purchase } from '../model/purchase';
import { PurchaseItemsList } from '../model/purchaseItemsList';
import { PurchaseList } from '../model/purchaseList';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PurchaseControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * View a list of available purchases
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPurchasesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<PurchaseList>;
    public getAllPurchasesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PurchaseList>>;
    public getAllPurchasesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PurchaseList>>;
    public getAllPurchasesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<PurchaseList>(`${this.basePath}/purchase`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get purchase by id
     * 
     * @param purchaseId purchaseId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPurchaseByIdUsingGET(purchaseId: string, observe?: 'body', reportProgress?: boolean): Observable<Purchase>;
    public getPurchaseByIdUsingGET(purchaseId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Purchase>>;
    public getPurchaseByIdUsingGET(purchaseId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Purchase>>;
    public getPurchaseByIdUsingGET(purchaseId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (purchaseId === null || purchaseId === undefined) {
            throw new Error('Required parameter purchaseId was null or undefined when calling getPurchaseByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Purchase>(`${this.basePath}/purchase/${encodeURIComponent(String(purchaseId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update purchase
     * 
     * @param purchaseItemsList purchaseItemsList
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public savePurchaseUsingPUT(purchaseItemsList: PurchaseItemsList, observe?: 'body', reportProgress?: boolean): Observable<PurchaseItemsList>;
    public savePurchaseUsingPUT(purchaseItemsList: PurchaseItemsList, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PurchaseItemsList>>;
    public savePurchaseUsingPUT(purchaseItemsList: PurchaseItemsList, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PurchaseItemsList>>;
    public savePurchaseUsingPUT(purchaseItemsList: PurchaseItemsList, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (purchaseItemsList === null || purchaseItemsList === undefined) {
            throw new Error('Required parameter purchaseItemsList was null or undefined when calling savePurchaseUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<PurchaseItemsList>(`${this.basePath}/purchase`,
            purchaseItemsList,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
