/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { SupplierRefund } from '../model/supplierRefund';
import { SupplierRefundList } from '../model/supplierRefundList';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SupplierRefundControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * View a list of available supplier refunds
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllSupplierRefundsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<SupplierRefundList>;
    public getAllSupplierRefundsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SupplierRefundList>>;
    public getAllSupplierRefundsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SupplierRefundList>>;
    public getAllSupplierRefundsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<SupplierRefundList>(`${this.basePath}/supplier-refund`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get supplier refund by id
     * 
     * @param supplierRefundId supplierRefundId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSupplierRefundByIdUsingGET(supplierRefundId: string, observe?: 'body', reportProgress?: boolean): Observable<SupplierRefund>;
    public getSupplierRefundByIdUsingGET(supplierRefundId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SupplierRefund>>;
    public getSupplierRefundByIdUsingGET(supplierRefundId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SupplierRefund>>;
    public getSupplierRefundByIdUsingGET(supplierRefundId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (supplierRefundId === null || supplierRefundId === undefined) {
            throw new Error('Required parameter supplierRefundId was null or undefined when calling getSupplierRefundByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<SupplierRefund>(`${this.basePath}/supplier-refund/${encodeURIComponent(String(supplierRefundId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update supplier refund
     * 
     * @param supplierRefund supplierRefund
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSupplierRefundUsingPUT(supplierRefund: SupplierRefund, observe?: 'body', reportProgress?: boolean): Observable<SupplierRefund>;
    public updateSupplierRefundUsingPUT(supplierRefund: SupplierRefund, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SupplierRefund>>;
    public updateSupplierRefundUsingPUT(supplierRefund: SupplierRefund, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SupplierRefund>>;
    public updateSupplierRefundUsingPUT(supplierRefund: SupplierRefund, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (supplierRefund === null || supplierRefund === undefined) {
            throw new Error('Required parameter supplierRefund was null or undefined when calling updateSupplierRefundUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<SupplierRefund>(`${this.basePath}/supplier-refund`,
            supplierRefund,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
