/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChemicalTest } from './chemicalTest';
import { Sale } from './sale';


export interface CustomerPayment { 
    amount?: number;
    chemicalTest?: ChemicalTest;
    code?: string;
    createdby?: string;
    createddate?: Date;
    date?: string;
    description?: string;
    id?: number;
    modifiedby?: string;
    modifieddate?: Date;
    paymenttype?: string;
    ref?: string;
    responseCode?: string;
    responseValues?: Array<string>;
    sale?: Sale;
    status?: number;
    statusDescription?: string;
    userId?: string;
}
