/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Order } from './order';


export interface Customer { 
    address?: string;
    contact1?: string;
    contact2?: string;
    createdby?: string;
    createddate?: Date;
    description?: string;
    email?: string;
    fax?: string;
    id?: number;
    modifiedby?: string;
    modifieddate?: Date;
    name?: string;
    orderCount?: number;
    orders?: Array<Order>;
    responseCode?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    type?: string;
    userId?: string;
}
