/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Delivery } from './delivery';
import { DeliveryEmployeeId } from './deliveryEmployeeId';
import { Employee } from './employee';


export interface DeliveryEmployee { 
    createdby?: string;
    createddate?: Date;
    delivery?: Delivery;
    deliveryEmployeeId?: DeliveryEmployeeId;
    description?: string;
    employee?: Employee;
    modifiedby?: string;
    modifieddate?: Date;
    responseCode?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    userId?: string;
}
