/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeliveryEmployee } from './deliveryEmployee';
import { Sale } from './sale';
import { Vehicle } from './vehicle';


export interface Delivery { 
    code?: string;
    createdby?: string;
    createddate?: Date;
    date?: string;
    deliveryEmployeeList?: Array<DeliveryEmployee>;
    deliveryaddress?: string;
    deliverycontactname?: string;
    deliverycontactno?: string;
    deliverynote?: string;
    description?: string;
    id?: number;
    modifiedby?: string;
    modifieddate?: Date;
    responseCode?: string;
    responseValues?: Array<string>;
    sale?: Sale;
    status?: number;
    statusDescription?: string;
    userId?: string;
    vehicle?: Vehicle;
}
