/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Disposal } from './disposal';
import { DisposalInventoryId } from './disposalInventoryId';
import { Inventory } from './inventory';


export interface DisposalInventory {
    createdby?: string;
    createddate?: Date;
    description?: string;
    disposal?: Disposal;
    disposalInventoryId?: DisposalInventoryId;
    inventory?: Inventory;
    modifiedby?: string;
    modifieddate?: Date;
    qty?: number;
    responseCode?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    userId?: string;
}
