/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DisposalInventory } from './disposalInventory';


export interface Disposal { 
    code?: string;
    createdby?: string;
    createddate?: Date;
    date?: string;
    description?: string;
    disposalInventoryList?: Array<DisposalInventory>;
    id?: number;
    modifiedby?: string;
    modifieddate?: Date;
    reason?: string;
    responseCode?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    userId?: string;
}
