/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { User } from './user';


export interface EmployeeUser { 
    description?: string;
    employee?: Employee;
    responseCode?: string;
    responseValues?: Array<string>;
    roleNameList?: Array<string>;
    user?: User;
}
