/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Inventory } from './inventory';
import { Item } from './item';


export interface InventoryItem { 
    inventory?: Inventory;
    item?: Item;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
}
