/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Notification { 
    createdby?: string;
    createddate?: Date;
    description?: string;
    dodelivered?: string;
    doreceived?: string;
    dosend?: string;
    id?: number;
    link?: string;
    message?: string;
    modifiedby?: string;
    modifieddate?: Date;
    responseCode?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    type?: string;
    userId?: string;
    userName?: string;
}
