/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Module } from './module';
import { PrivilegeId } from './privilegeId';
import { Role } from './role';


export interface Privilege { 
    add?: string;
    createdby?: string;
    createddate?: Date;
    _delete?: string;
    description?: string;
    getAll?: string;
    getBasic?: string;
    modifiedby?: string;
    modifieddate?: Date;
    module?: Module;
    privilegeId?: PrivilegeId;
    responseCode?: string;
    responseValues?: Array<string>;
    role?: Role;
    status?: number;
    statusDescription?: string;
    update?: string;
    userId?: string;
}
