/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Item } from './item';
import { ProductInbound } from './productInbound';
import { ProductInboundItemId } from './productInboundItemId';


export interface ProductInboundItem { 
    createdby?: string;
    createddate?: Date;
    doexpire?: string;
    item?: Item;
    modifiedby?: string;
    modifieddate?: Date;
    productInbound?: ProductInbound;
    productInboundItemId?: ProductInboundItemId;
    qty?: number;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    userId?: string;
}
