/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PurchaseOrder } from './purchaseOrder';
import { PurchaseOrderItems } from './purchaseOrderItems';
import { SupplierPayment } from './supplierPayment';


export interface PurchaseOrderItemsList { 
    purchaseOrder?: PurchaseOrder;
    purchaseOrderItems?: Array<PurchaseOrderItems>;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    supplierPayment?: SupplierPayment;
    userId?: string;
}
