/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PurchaseItems } from './purchaseItems';
import { PurchaseOrder } from './purchaseOrder';
import { Supplier } from './supplier';
import { SupplierPayment } from './supplierPayment';


export interface Purchase {
    code?: string;
    createdby?: string;
    createddate?: Date;
    date?: string;
    description?: string;
    id?: number;
    modifiedby?: string;
    modifieddate?: Date;
    purchaseItems?: Array<PurchaseItems>;
    purchaseOrder?: PurchaseOrder;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    supplier?: Supplier;
    supplierPayment?: SupplierPayment;
    total?: number;
    userId?: string;
    purchaseTotal?: string;
    purchaseOrderId?: number;
}
