/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Item } from './item';
import { Purchase } from './purchase';
import { PurchaseItemId } from './purchaseItemId';


export interface PurchaseItems { 
    acceptedqty?: number;
    createdby?: string;
    createddate?: Date;
    doexpire?: string;
    item?: Item;
    itemId?: number;
    itemName?: string;
    modifiedby?: string;
    modifieddate?: Date;
    purchase?: Purchase;
    purchaseItemId?: PurchaseItemId;
    qty?: number;
    rejectedqty?: number;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    unitprice?: number;
    userId?: string;
}
