/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Purchase } from './purchase';
import { PurchaseOrderItems } from './purchaseOrderItems';
import { Supplier } from './supplier';


export interface PurchaseOrder { 
    code?: string;
    createdby?: string;
    createddate?: Date;
    description?: string;
    doordered?: string;
    dorecived?: string;
    dorequired?: string;
    id?: number;
    modifiedby?: string;
    modifieddate?: Date;
    purchase?: Purchase;
    purchaseOrderItems?: Array<PurchaseOrderItems>;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    supplier?: Supplier;
    supplierId?: number;
    supplierName?: string;
    supplierType?: string;
    userId?: string;
}
