/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerPayment } from './customerPayment';
import { Delivery } from './delivery';
import { Disposal } from './disposal';
import { Order } from './order';
import { Purchase } from './purchase';
import { PurchaseOrder } from './purchaseOrder';
import { Sale } from './sale';
import { SupplierPayment } from './supplierPayment';
import { SupplierRefund } from './supplierRefund';
import { SupplierReturn } from './supplierReturn';


export interface ReportResponse { 
    customerPaymentList?: Array<CustomerPayment>;
    deliveryList?: Array<Delivery>;
    disposalList?: Array<Disposal>;
    orderList?: Array<Order>;
    purchaseList?: Array<Purchase>;
    purchaseOrderList?: Array<PurchaseOrder>;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    saleList?: Array<Sale>;
    supplierPaymentList?: Array<SupplierPayment>;
    supplierRefundList?: Array<SupplierRefund>;
    supplierReturnList?: Array<SupplierReturn>;
}
