/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Inventory } from './inventory';
import { Sale } from './sale';
import { SaleInventoryId } from './saleInventoryId';


export interface SaleInventory { 
    createdby?: string;
    createddate?: Date;
    inventory?: Inventory;
    modifiedby?: string;
    modifieddate?: Date;
    qty?: number;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    sale?: Sale;
    saleInventoryId?: SaleInventoryId;
    status?: number;
    statusDescription?: string;
    unitprice?: number;
    userId?: string;
}
