/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Supplier } from './supplier';
import { SupplierReplaceInventory } from './supplierReplaceInventory';
import { SupplierReturnInventory } from './supplierReturnInventory';


export interface SupplierReturn { 
    code?: string;
    createdby?: string;
    createddate?: Date;
    dorecived?: string;
    doreturned?: string;
    id?: number;
    modifiedby?: string;
    modifieddate?: Date;
    reason?: string;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    supplier?: Supplier;
    supplierReplaceInventories?: Array<SupplierReplaceInventory>;
    supplierReturnInventories?: Array<SupplierReturnInventory>;
    userId?: string;
}
