/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface User { 
    createdby?: string;
    createddate?: Date;
    description?: string;
    failedAttempts?: number;
    id?: string;
    modifiedby?: string;
    modifieddate?: Date;
    password?: string;
    responseCode?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    token?: string;
    userId?: string;
    userName?: string;
    userRoles?: Array<UserRole>;
}
