/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Role } from './role';
import { User } from './user';
import { UserRoleId } from './userRoleId';


export interface UserRole { 
    createdby?: string;
    createddate?: Date;
    description?: string;
    modifiedby?: string;
    modifieddate?: Date;
    responseCode?: string;
    responseValues?: Array<string>;
    role?: Role;
    status?: number;
    user?: User;
    userId?: string;
    userRoleId?: UserRoleId;
}
