/**
 * Water Solution Inventory Spring Boot App
 * Spring Boot REST API
 *
 * OpenAPI spec version: 1.0
 * Contact: watersolution@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Delivery } from './delivery';
import { VehicleType } from './vehicleType';
import { VehicleVehicleFacility } from './vehicleVehicleFacility';


export interface Vehicle { 
    brand?: string;
    createdby?: string;
    createddate?: Date;
    deliveryList?: Array<Delivery>;
    description?: string;
    id?: number;
    modal?: string;
    modifiedby?: string;
    modifieddate?: Date;
    no?: string;
    responseCode?: string;
    responseDescription?: string;
    responseValues?: Array<string>;
    status?: number;
    statusDescription?: string;
    type?: string;
    userId?: string;
    vehicleFacilityList?: Array<VehicleVehicleFacility>;
    vehicleType?: VehicleType;
}
